# inference_esp32.py — On-device Rock Paper Scissors CNN inference
# ENMGT 5400 — MicroPython for XIAO ESP32S3 Sense
#
# Prerequisites (copy to ESP32 flash first):
#   weights_esp32.py  — generated by export_weights.py on laptop
#
# Usage:
#   Run via Thonny or: mpremote run inference_esp32.py
#
# What it does:
#   1. Captures one frame from the camera
#   2. Resizes 160×120 → 32×32 (center crop + every-3rd-pixel, same as preprocess.py)
#   3. Converts to grayscale → Sobel edge map (same as train.py PREPROCESSING='sobel')
#   4. Runs CNN forward pass (uses ulab if available, pure Python otherwise)
#   5. Prints predicted class + confidence over serial

import gc
import math
import struct

gc.collect()

# ─── Detect available libraries ──────────────────────────────────────────────
try:
    import ulab.numpy as unp
    HAS_ULAB = True
    print("[init] ulab available — fast inference path")
except ImportError:
    HAS_ULAB = False
    print("[init] ulab not available — pure Python path (slow but correct)")

# ─── Weight scales (printed by export_weights.py, hardcoded here) ─────────────
CLASSES = ['rock', 'paper', 'scissors']

SCALES = {
    'CONV1':  {'W': 0.00269486, 'B': 0.00024275, 'W_shape': [3,3,1,32],     'B_shape': [32]},
    'CONV2':  {'W': 0.00162963, 'B': 0.00253862, 'W_shape': [3,3,32,64],    'B_shape': [64]},
    'CONV3':  {'W': 0.00081625, 'B': 0.00341616, 'W_shape': [3,3,64,128],   'B_shape': [128]},
    'DENSE1': {'W': 0.00059559, 'B': 0.00009572, 'W_shape': [2048,128],     'B_shape': [128]},
    'DENSE2': {'W': 0.00172469, 'B': 0.00004008, 'W_shape': [128,3],        'B_shape': [3]},
}
LAYER_ORDER = ['CONV1', 'CONV2', 'CONV3', 'DENSE1', 'DENSE2']

# ─── Load weights from binary file ────────────────────────────────────────────
print("[init] Loading weights.bin...")

_weights = {}

def _load_weights():
    import math as _math
    with open('weights.bin', 'rb') as f:
        for name in LAYER_ORDER:
            s = SCALES[name]
            w_size = 1
            for d in s['W_shape']:
                w_size *= d
            b_size = s['B_shape'][0]
            _weights[name + '_W'] = bytearray(f.read(w_size))
            _weights[name + '_B'] = bytearray(f.read(b_size))

_load_weights()
gc.collect()
print("[init] Weights loaded. Free RAM: {} bytes".format(gc.mem_free()))


# ─── Image preprocessing ──────────────────────────────────────────────────────

def rgb565_to_gray(pixel_hi, pixel_lo):
    """
    Convert one RGB565 pixel (2 bytes, big-endian) to grayscale 0..255.
    RGB565: RRRRRGGGGGGBBBBB
    """
    px = (pixel_hi << 8) | pixel_lo
    r = ((px >> 11) & 0x1F) * 255 // 31
    g = ((px >> 5)  & 0x3F) * 255 // 63
    b = ( px        & 0x1F) * 255 // 31
    # ITU-R BT.601 luma approximation (integer)
    return (r * 77 + g * 150 + b * 29) >> 8


def capture_and_preprocess(cam):
    """
    Capture a frame, center-crop 96×96, downsample every-3rd-pixel to 32×32,
    convert to grayscale, apply Sobel, return 32×32 list-of-lists (float 0..1).
    """
    frame = cam.capture()   # 160×120 RGB565, big-endian, 38400 bytes

    W_IN, H_IN = 160, 120
    CROP = 96
    top  = (H_IN - CROP) // 2   # 12
    left = (W_IN - CROP) // 2   # 32

    # Extract 96×96 grayscale patch by sampling every 3rd pixel → 32×32
    SIZE = 32
    gray = [[0] * SIZE for _ in range(SIZE)]

    for row in range(SIZE):
        src_row = top + row * 3
        for col in range(SIZE):
            src_col = left + col * 3
            byte_idx = (src_row * W_IN + src_col) * 2
            hi = frame[byte_idx]
            lo = frame[byte_idx + 1]
            gray[row][col] = rgb565_to_gray(hi, lo)

    del frame
    gc.collect()

    # Sobel edge detection (3×3, with zero-padding)
    Kx = [[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]]
    Ky = [[-1, -2, -1], [0, 0, 0], [1, 2, 1]]

    sobel = [[0.0] * SIZE for _ in range(SIZE)]
    max_val = 0.0

    for r in range(SIZE):
        for c in range(SIZE):
            gx = gy = 0
            for dr in range(-1, 2):
                for dc in range(-1, 2):
                    rr = r + dr
                    cc = c + dc
                    if 0 <= rr < SIZE and 0 <= cc < SIZE:
                        px = gray[rr][cc]
                    else:
                        px = 0
                    gx += Kx[dr + 1][dc + 1] * px
                    gy += Ky[dr + 1][dc + 1] * px
            mag = math.sqrt(gx * gx + gy * gy)
            sobel[r][c] = mag
            if mag > max_val:
                max_val = mag

    # Normalize to [0.0, 1.0]
    if max_val > 0:
        for r in range(SIZE):
            for c in range(SIZE):
                sobel[r][c] /= max_val

    return sobel  # 32×32 list-of-lists, float


# ─── CNN forward pass helpers ─────────────────────────────────────────────────

def dequant(byte_val, scale):
    """Convert signed int8 (stored as unsigned in bytearray) to float."""
    v = byte_val if byte_val < 128 else byte_val - 256
    return v * scale


def relu(x):
    return x if x > 0.0 else 0.0


def softmax(logits):
    max_l = max(logits)
    exps  = [math.exp(l - max_l) for l in logits]
    total = sum(exps)
    return [e / total for e in exps]


# ─── Pure Python forward pass ─────────────────────────────────────────────────

def conv2d_maxpool_pure(inp, layer_name):
    """
    Conv2D (same padding) + ReLU + MaxPool2D(2×2).
    inp: H×W×C_in list-of-lists-of-lists
    Returns: (H/2) × (W/2) × n_filters
    """
    W_data   = _weights[layer_name + '_W']
    b_data   = _weights[layer_name + '_B']
    W_shape  = SCALES[layer_name]['W_shape']   # [kH, kW, C_in, n_filters]
    W_scale  = SCALES[layer_name]['W']
    b_scale  = SCALES[layer_name]['B']

    kH, kW, C_in, n_f = W_shape
    H = len(inp)
    C = n_f

    # Pre-dequantize biases
    biases = [dequant(b_data[f], b_scale) for f in range(n_f)]

    # Output after conv (same padding), before pool
    conv_out = [[[0.0] * n_f for _ in range(H)] for _ in range(H)]

    pad = kH // 2  # = 1 for 3×3 kernel

    for r in range(H):
        for c in range(H):
            for f in range(n_f):
                acc = biases[f]
                for dr in range(kH):
                    for dc in range(kW):
                        rr = r - pad + dr
                        cc = c - pad + dc
                        if 0 <= rr < H and 0 <= cc < H:
                            for ci in range(C_in):
                                w_idx = ((f * kH + dr) * kW + dc) * C_in + ci
                                w_val = dequant(W_data[w_idx], W_scale)
                                conv_out[r][c][f] += w_val * inp[rr][cc][ci]
                conv_out[r][c][f] = relu(conv_out[r][c][f])

    # MaxPool 2×2 → halve spatial dims
    H2 = H // 2
    pool_out = [[[0.0] * n_f for _ in range(H2)] for _ in range(H2)]
    for r in range(H2):
        for c in range(H2):
            for f in range(n_f):
                pool_out[r][c][f] = max(
                    conv_out[r*2][c*2][f],     conv_out[r*2][c*2+1][f],
                    conv_out[r*2+1][c*2][f],   conv_out[r*2+1][c*2+1][f]
                )

    return pool_out


def dense_pure(flat_inp, layer_name, activation=None):
    """Fully-connected layer. activation='relu' or None (linear)."""
    W_data  = _weights[layer_name + '_W']
    b_data  = _weights[layer_name + '_B']
    W_shape = SCALES[layer_name]['W_shape']   # [in_dim, out_dim]
    W_scale = SCALES[layer_name]['W']
    b_scale = SCALES[layer_name]['B']

    in_dim, out_dim = W_shape
    biases = [dequant(b_data[j], b_scale) for j in range(out_dim)]

    out = list(biases)
    for j in range(out_dim):
        for i in range(in_dim):
            w_val = dequant(W_data[i * out_dim + j], W_scale)
            out[j] += w_val * flat_inp[i]
        if activation == 'relu':
            out[j] = relu(out[j])

    return out


def forward_pure(sobel_2d):
    """Full CNN forward pass, pure Python. sobel_2d: 32×32 list-of-lists."""
    SIZE = 32

    # Wrap to 32×32×1
    inp = [[[sobel_2d[r][c]] for c in range(SIZE)] for r in range(SIZE)]
    gc.collect()

    print("[fwd] conv1...")
    x = conv2d_maxpool_pure(inp, 'CONV1')   # → 16×16×32
    del inp; gc.collect()

    print("[fwd] conv2...")
    x = conv2d_maxpool_pure(x,   'CONV2')   # → 8×8×64
    gc.collect()

    print("[fwd] conv3...")
    x = conv2d_maxpool_pure(x,   'CONV3')   # → 4×4×128
    gc.collect()

    # Flatten 4×4×128 → 2048
    flat = []
    for r in x:
        for c in r:
            flat.extend(c)
    del x; gc.collect()

    print("[fwd] dense1...")
    x = dense_pure(flat, 'DENSE1', activation='relu')  # → 128
    del flat; gc.collect()

    print("[fwd] dense2...")
    logits = dense_pure(x, 'DENSE2')  # → 3
    return softmax(logits)


# ─── ulab fast forward pass ────────────────────────────────────────────────────

def forward_ulab(sobel_2d):
    """CNN forward pass using ulab.numpy for fast matrix ops."""
    SIZE = 32

    # Convert sobel to ulab array (32×32×1)
    flat_data = []
    for row in sobel_2d:
        flat_data.extend(row)
    inp = unp.array(flat_data, dtype=unp.float32).reshape((1, SIZE, SIZE, 1))

    def get_w(name):
        arr = unp.frombuffer(_weights[name + '_W'], dtype=unp.int8).astype(unp.float32) * SCALES[name]['W']
        return arr.reshape(SCALES[name]['W_shape'])

    def get_b(name):
        arr = unp.frombuffer(_weights[name + '_B'], dtype=unp.int8).astype(unp.float32) * SCALES[name]['B']
        return arr

    # Dense layers (ulab handles matrix multiply)
    # For conv layers we still use the pure Python loop — ulab doesn't have conv2d.
    # But ulab's dense is ~100x faster for the 2048×128 bottleneck.

    # Run conv layers with pure Python (they're small: 32×32, 16×16, 8×8)
    sobel_list = [[sobel_2d[r][c] for c in range(SIZE)] for r in range(SIZE)]
    inp_3d = [[[sobel_list[r][c]] for c in range(SIZE)] for r in range(SIZE)]

    print("[fwd-ulab] conv1...")
    x = conv2d_maxpool_pure(inp_3d, 'CONV1')
    del inp_3d; gc.collect()

    print("[fwd-ulab] conv2...")
    x = conv2d_maxpool_pure(x, 'CONV2')
    gc.collect()

    print("[fwd-ulab] conv3...")
    x = conv2d_maxpool_pure(x, 'CONV3')
    gc.collect()

    # Flatten
    flat = []
    for r in x:
        for c in r:
            flat.extend(c)
    del x; gc.collect()

    # Dense layers with ulab matrix multiply (fast)
    print("[fwd-ulab] dense1 (ulab)...")
    flat_arr = unp.array(flat, dtype=unp.float32)
    W1 = get_w('DENSE1'); b1 = get_b('DENSE1')
    x1 = unp.dot(flat_arr, W1) + b1
    # ReLU
    x1 = unp.maximum(x1, unp.zeros(len(b1)))

    print("[fwd-ulab] dense2 (ulab)...")
    W2 = get_w('DENSE2'); b2 = get_b('DENSE2')
    logits_arr = unp.dot(x1, W2) + b2
    logits = list(logits_arr)
    return softmax(logits)


# ─── Main ────────────────────────────────────────────────────────────────────

def main():
    print("\n=== Rock Paper Scissors Inference ===")
    print("Preprocessing: Sobel edge detection on 32×32 grayscale")
    print("Forward pass : {}".format("ulab (fast)" if HAS_ULAB else "pure Python (slow — please wait)"))
    print()

    # Init camera
    try:
        from camera import Camera
        cam = Camera()
        print("[camera] Initialized. Capturing frame...")
        # Warm up (first frame is often corrupted)
        for _ in range(3):
            _ = cam.capture()
        frame_available = True
    except Exception as e:
        print("[camera] ERROR:", e)
        frame_available = False

    if frame_available:
        print("[preprocess] Resizing and applying Sobel...")
        sobel = capture_and_preprocess(cam)
        gc.collect()
        print("[preprocess] Done. Free RAM: {} bytes".format(gc.mem_free()))
    else:
        print("[camera] Camera unavailable — generating test pattern (zeros)")
        sobel = [[0.0] * 32 for _ in range(32)]

    # Forward pass
    print("[inference] Running forward pass...")
    gc.collect()
    if HAS_ULAB:
        scores = forward_ulab(sobel)
    else:
        scores = forward_pure(sobel)

    gc.collect()

    # Results
    best_idx  = scores.index(max(scores))
    best_cls  = CLASSES[best_idx]
    best_conf = scores[best_idx] * 100.0

    print()
    print("=" * 35)
    print("Predicted: {} ({:.1f}%)".format(best_cls, best_conf))
    print()
    for i, cls in enumerate(CLASSES):
        bar = '#' * int(scores[i] * 20)
        print("  {:8s} {:5.1f}%  {}".format(cls, scores[i] * 100, bar))
    print("=" * 35)


main()
