# realtime_esp32.py — Continuous Rock Paper Scissors classification
# ENMGT 5400 — MicroPython for XIAO ESP32S3 Sense
# Written with assistance from Claude (Anthropic, claude.ai)
#
# Prerequisites (must be on ESP32 flash):
#   weights.bin  — generated by export_weights.py on laptop
#
# Usage: Run via Thonny or mpremote run realtime_esp32.py
# Stop:  Ctrl+C in Thonny
#
# Optimization vs inference_esp32.py:
#   Weights are dequantized ONCE at startup into float lists.
#   Inner conv/dense loops do a single list lookup instead of calling
#   dequant() millions of times — ~3-10x faster per frame.

import gc
import math
import time

gc.collect()

# ─── Config ──────────────────────────────────────────────────────────────────
CLASSES     = ['rock', 'paper', 'scissors']
LAYER_ORDER = ['CONV1', 'CONV2', 'CONV3', 'DENSE1', 'DENSE2']

SCALES = {
    # Conv shapes stored as [n_f, kH, kW, C_in] after transpose in export_weights.py
    'CONV1':  {'W': 0.01555518, 'B': 0.00060575, 'W_shape': [4,3,3,1],   'B_shape': [4]},
    'CONV2':  {'W': 0.00718084, 'B': 0.00498709, 'W_shape': [8,3,3,4],   'B_shape': [8]},
    'CONV3':  {'W': 0.00247606, 'B': 0.00201385, 'W_shape': [16,3,3,8],  'B_shape': [16]},
    'DENSE1': {'W': 0.00151231, 'B': 0.00020526, 'W_shape': [256,32],    'B_shape': [32]},
    'DENSE2': {'W': 0.00313080, 'B': 0.00007249, 'W_shape': [32,3],      'B_shape': [3]},
}

# ─── Step 1: Load raw weights from binary file ────────────────────────────────
print("[init] Loading weights.bin...")
_raw = {}
with open('weights.bin', 'rb') as f:
    for name in LAYER_ORDER:
        s = SCALES[name]
        w_size = 1
        for d in s['W_shape']:
            w_size *= d
        _raw[name + '_W'] = bytearray(f.read(w_size))
        _raw[name + '_B'] = bytearray(f.read(s['B_shape'][0]))
gc.collect()
print("[init] Raw weights loaded. Free RAM: {} B".format(gc.mem_free()))

# ─── Step 2: Precompute float weights (the key optimization) ─────────────────
# Converts int8 bytearrays → Python float lists ONCE at startup.
# Inner loops then do a single list index instead of calling dequant() each time.
print("[init] Precomputing float weights (one-time, ~5-15 sec)...")

_fw = {}   # float weights
_fb = {}   # float biases

for name in LAYER_ORDER:
    ws = SCALES[name]['W']
    bs = SCALES[name]['B']
    raw_w = _raw[name + '_W']
    raw_b = _raw[name + '_B']
    _fw[name] = [(b if b < 128 else b - 256) * ws for b in raw_w]
    _fb[name] = [(b if b < 128 else b - 256) * bs for b in raw_b]
    print("  {} done ({} weights)".format(name, len(_fw[name])))
    gc.collect()

del _raw
gc.collect()
print("[init] Precompute done. Free RAM: {} B".format(gc.mem_free()))


# ─── Image preprocessing ──────────────────────────────────────────────────────

def capture_and_preprocess(cam):
    """160×120 RGB565 → 32×32 Sobel float list (flat, length 1024)."""
    frame = cam.capture()

    W_IN, H_IN = 160, 120
    top  = (H_IN - 96) // 2   # 12
    left = (W_IN - 96) // 2   # 32
    SIZE = 32

    # Extract 32×32 grayscale by sampling every 3rd pixel from 96×96 center crop
    gray = [0] * (SIZE * SIZE)
    for row in range(SIZE):
        src_row = top + row * 3
        base    = src_row * W_IN
        for col in range(SIZE):
            src_col = left + col * 3
            idx = (base + src_col) * 2
            hi = frame[idx]; lo = frame[idx + 1]
            px = (hi << 8) | lo
            r = ((px >> 11) & 0x1F) * 255 // 31
            g = ((px >> 5)  & 0x3F) * 255 // 63
            b = ( px        & 0x1F) * 255 // 31
            gray[row * SIZE + col] = (r * 77 + g * 150 + b * 29) >> 8

    del frame
    gc.collect()

    # Sobel (3×3, zero-pad)
    Kx = (-1, 0, 1, -2, 0, 2, -1, 0, 1)
    Ky = (-1,-2,-1,  0, 0, 0,  1, 2, 1)
    sobel = [0.0] * (SIZE * SIZE)
    max_val = 0.0

    for r in range(SIZE):
        for c in range(SIZE):
            gx = gy = 0
            ki = 0
            for dr in (-1, 0, 1):
                rr = r + dr
                for dc in (-1, 0, 1):
                    cc = c + dc
                    if 0 <= rr < SIZE and 0 <= cc < SIZE:
                        px = gray[rr * SIZE + cc]
                    else:
                        px = 0
                    gx += Kx[ki] * px
                    gy += Ky[ki] * px
                    ki += 1
            mag = math.sqrt(gx * gx + gy * gy)
            sobel[r * SIZE + c] = mag
            if mag > max_val:
                max_val = mag

    if max_val > 0:
        inv = 1.0 / max_val
        for i in range(SIZE * SIZE):
            sobel[i] *= inv

    return sobel  # flat list of 1024 floats


# ─── CNN forward pass (optimized: uses precomputed float lists) ───────────────

def conv_maxpool(inp_flat, H, layer_name):
    """
    Conv2D same-padding + ReLU + MaxPool2×2 using precomputed float weights.
    inp_flat: flat list length H*H*C_in
    Returns: flat list length (H/2)*(H/2)*n_f
    """
    fw   = _fw[layer_name]
    fb   = _fb[layer_name]
    n_f, kH, kW, C_in = SCALES[layer_name]['W_shape']  # stored as [n_f, kH, kW, C_in]
    pad  = 1  # kH//2

    H2 = H // 2
    out = [0.0] * (H2 * H2 * n_f)

    for r in range(H):
        for c in range(H):
            for f in range(n_f):
                acc = fb[f]
                ki  = f * kH * kW * C_in   # start index in fw for filter f
                for dr in range(kH):
                    rr = r - pad + dr
                    for dc in range(kW):
                        cc = c - pad + dc
                        if 0 <= rr < H and 0 <= cc < H:
                            inp_base = (rr * H + cc) * C_in
                            for ci in range(C_in):
                                acc += fw[ki + ci] * inp_flat[inp_base + ci]
                        ki += C_in
                # ReLU — store in 2×downsampled output via max-pool accumulation
                # We accumulate the max for each 2×2 window
                if acc > 0.0:
                    out_r = r // 2
                    out_c = c // 2
                    out_idx = (out_r * H2 + out_c) * n_f + f
                    if acc > out[out_idx]:
                        out[out_idx] = acc

    return out


def dense(inp, layer_name, relu_act=False):
    """Fully-connected layer using precomputed float weights."""
    fw      = _fw[layer_name]
    fb      = _fb[layer_name]
    in_dim, out_dim = SCALES[layer_name]['W_shape']
    out = list(fb)   # copy biases
    for j in range(out_dim):
        acc = out[j]
        base = j
        for i in range(in_dim):
            acc += fw[base] * inp[i]
            base += out_dim
        if relu_act and acc < 0.0:
            acc = 0.0
        out[j] = acc
    return out


def forward(sobel_flat):
    """Full CNN forward pass. sobel_flat: 1024 floats (32×32×1)."""
    x = conv_maxpool(sobel_flat, 32, 'CONV1')
    gc.collect()
    x = conv_maxpool(x,          16, 'CONV2')
    gc.collect()
    x = conv_maxpool(x,           8, 'CONV3')
    gc.collect()
    x = dense(x, 'DENSE1', relu_act=True)           # → 128
    gc.collect()
    logits = dense(x, 'DENSE2')                     # → 3

    # Softmax
    max_l = max(logits)
    exps  = [math.exp(l - max_l) for l in logits]
    total = sum(exps)
    return [e / total for e in exps]


# ─── Main loop ────────────────────────────────────────────────────────────────

def main():
    from camera import Camera
    cam = Camera()
    print("[camera] Warming up (5 frames)...")
    for _ in range(5):
        cam.capture()
    print("[camera] Ready.\n")

    print("=" * 45)
    print("Rock Paper Scissors — Real-Time Classification")
    print("Hold a gesture in front of the camera.")
    print("Press Ctrl+C to stop and see accuracy summary.")
    print("=" * 45)

    frame_num   = 0
    correct     = 0
    total_asked = 0

    while True:
        t0 = time.ticks_ms()

        sobel = capture_and_preprocess(cam)
        gc.collect()

        scores   = forward(sobel)
        elapsed  = time.ticks_diff(time.ticks_ms(), t0) / 1000.0

        best_idx  = scores.index(max(scores))
        best_cls  = CLASSES[best_idx]
        best_conf = scores[best_idx] * 100.0

        frame_num += 1
        print("Frame {:3d} | {:8s} {:5.1f}% | {:.1f}s  [r={:.0f}% p={:.0f}% s={:.0f}%]".format(
            frame_num, best_cls, best_conf, elapsed,
            scores[0]*100, scores[1]*100, scores[2]*100))

        gc.collect()


main()
